version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.0

jobs:
  test-only:
    docker: 
      - image: circleci/node:14.8.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
  test-and-deploy:
    docker: 
      - image: circleci/node:14.8.0
    steps:
      - checkout
      - aws-cli/setup
      - run: npm install
      - run: npm test
      - run: npm run upload
      
workflows:
  pure-paradise-server:
    jobs:
      - test-only:
          filters:
            branches:
              ignore: master 
      - test-and-deploy:
          filters:
            branches:
              only: master
    